name: Nexus Kernel Apollo
run-name: Nexus Kernel Apollo

on:
  push:
    branches: [ deep_sleep ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: nexgang/ubuntu:latest

    steps:
      - uses: actions/checkout@v3
      - name: Nexus Kernel Apollo
        run: bash build.sh null apollo null
        env:
           token: ${{ secrets.TOKEN }}
           chat_id: ${{ secrets.CHAT_ID }}
