name: Nexus Kernel Munch
run-name: Nexus Kernel Munch

on:
  push:
    branches: [ deep_sleep ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: nexgang/ubuntu:latest

    steps:
      - uses: actions/checkout@v3
      - name: Nexus Kernel Munch
        run: bash build.sh null munch null
        env:
           token: ${{ secrets.TOKEN }}
           chat_id: ${{ secrets.CHAT_ID }}
